# source database URL
# database URLs take the format of:
#   postgres://user:password@host:port/dbname
# we recommend a command which outputs a database URL
# so sensitive information is not included in this file
# we *highly recommend* you use sslmode=verify-full when possible
# see https://ankane.org/postgres-sslmode-explained for more info
from: $(some_command)?sslmode=require

# destination database URL
to: postgres://localhost:5432/myapp_development

# exclude tables
# exclude:
#   - schema_migrations
#   - ar_internal_metadata

# define groups
# groups:
#   group1:
#     - table1
#     - table2

# protect sensitive information
data_rules:
  email: unique_email
  phone: unique_phone
  last_name: random_letter
  birthday: random_date
  encrypted_*: null
